/** Asset paths mirrored from iSensorApp */
export const IMG = {
  splashLogo: '/assets/images/splash-logo.png',
  mainLogo: '/assets/images/main-logo.png',
  mainTire: '/assets/images/main-tire.png',
  frontCar: '/assets/images/front-car.png',
  rearCar: '/assets/images/rear-car.png',
  tireNormal: '/assets/images/normal-tire.png',
  tireCaution: '/assets/images/caution-tire.png',
  tireDanger: '/assets/images/danger-tire.png',
  insightsGood: '/assets/images/insights-goodtire.png',
  insightsCaution: '/assets/images/insights-cautiontire.png',
  insightsDanger: '/assets/images/insights-dangertire.png',
  csv: '/assets/icons/csv.svg',
  addTire: '/assets/icons/add-tire.svg',
  arrowDown: '/assets/icons/arrow-down.svg',
  lock: '/assets/icons/lock.svg',
  star: '/assets/icons/star.svg',
  insightsInfo: '/assets/icons/insights-info.svg',
  back: '/assets/icons/back.svg',
  statusInsights: {
    good: '/assets/icons/good-insights.svg',
    caution: '/assets/icons/caution-insights.svg',
    danger: '/assets/icons/danger-insights.svg',
  },
  truckInsights: {
    good: '/assets/icons/insights-good.svg',
    caution: '/assets/icons/insights-caution.svg',
    danger: '/assets/icons/insights-danger.svg',
  },
  insightsMetric: {
    pressure: '/assets/icons/insights-pressure.svg',
    temperature: '/assets/icons/insights-temperature.svg',
    load: '/assets/icons/insights-load.svg',
    nut: '/assets/icons/insights-nut.svg',
    align: '/assets/icons/insights-align.svg',
  },
  chevronCalendar: '/assets/icons/chevron-calendar.svg',
  checkpoint: '/assets/icons/checkpoint.svg',
  location: '/assets/icons/location.svg',
  recurrence: '/assets/icons/recurrence.svg',
  statusLog: {
    good: '/assets/icons/good-log.svg',
    caution: '/assets/icons/caution-log.svg',
    danger: '/assets/icons/danger-log.svg',
  },
  bluetooth: '/assets/icons/bluetooth.svg',
  notification: '/assets/icons/notification.svg',
  chevron: '/assets/icons/chevron.svg',
  ai: '/assets/icons/ai.svg',
  aiSpark: '/assets/icons/ai-spark.svg',
  aiReport: '/assets/icons/ai-report.svg',
  cancel: '/assets/icons/cancel.svg',
  btSetting: '/assets/icons/bluetooth-setting.svg',
  notifSetting: '/assets/icons/notification-setting.svg',
  helpSetting: '/assets/icons/help-setting.svg',
  supportSetting: '/assets/icons/support-setting.svg',
  pressureGauge: '/assets/images/pressure-gauge.png',
  pressurePin: {
    normal: '/assets/icons/good-pressure.svg',
    caution: '/assets/icons/caution-pressure.svg',
    danger: '/assets/icons/danger-pressure.svg',
  },
  metricIcon: {
    temperature: {
      normal: '/assets/icons/good-temperature.svg',
      caution: '/assets/icons/caution-temperature.svg',
      danger: '/assets/icons/danger-temperature.svg',
    },
    weight: {
      normal: '/assets/icons/good-weight.svg',
      caution: '/assets/icons/caution-weight.svg',
      danger: '/assets/icons/danger-weight.svg',
    },
    align: {
      normal: '/assets/icons/good-align.svg',
      caution: '/assets/icons/caution-align.svg',
      danger: '/assets/icons/danger-align.svg',
    },
    nut: {
      normal: '/assets/icons/good-nut.svg',
      caution: '/assets/icons/caution-nut.svg',
      danger: '/assets/icons/danger-nut.svg',
    },
  },
  tab: {
    home: '/assets/tabIcons/home.png',
    homeActive: '/assets/tabIcons/home-active.png',
    drive: '/assets/tabIcons/drive.png',
    driveActive: '/assets/tabIcons/drive-active.png',
    insights: '/assets/tabIcons/insights.png',
    insightsActive: '/assets/tabIcons/insights-active.png',
    setting: '/assets/tabIcons/setting.png',
    settingActive: '/assets/tabIcons/setting-active.png',
  },
} as const;

export const TIRE_IMG = {
  normal: IMG.tireNormal,
  caution: IMG.tireCaution,
  danger: IMG.tireDanger,
  offline: IMG.tireNormal,
} as const;
